Repository madrimas/siluets, pull requests merged in 2020-05, with the labels that each got.

#14 Firebase configuration close
  .gitignore
  src/common/Firebase.service.js
  src/main.js
  src/views/Training.vue
Labels: enhancement

#16 Basic authentication
  package.json
  src/common/Firebase.service.js
  src/store/actions.type.js
  src/store/home.module.js
  src/store/index.js
  src/store/mutations.type.js
  src/store/presets.module.js
  src/views/Home.vue
  src/views/PresetsCreator.vue
  yarn.lock
Labels: enhancement

#17 Preset creation polishing
  src/common/Firebase.service.js
  src/config/api.config.js
  src/store/actions.type.js
  src/store/presets.module.js
  src/views/Home.vue
  src/views/Measurements.vue
  src/views/Presets.vue
Labels: enhancement

#21 trainings can be displayed and saved
  src/common/Firebase.service.js
  src/store/mutations.type.js
  src/store/training.module.js
  src/views/Training.vue
Labels: bug

#23 true promises fetch
  src/common/Firebase.service.js
Labels: bug

#24 Removed null if user didn't provided reps in last set
  src/store/training.module.js
Labels: bug

#25 UI is no longer stuck if there is no exercises in category
  src/store/presetCreator.module.js
Labels: bug

#27 Measurements
  src/common/Firebase.service.js
  src/store/actions.type.js
  src/store/index.js
  src/store/measurements.module.js
  src/store/mutations.type.js
  src/views/Measurements.vue
Labels: enhancement

#28 Branch to improve small things
  src/store/training.module.js
  src/views/PresetsCreator.vue
Labels: refactoring

#29 Improvement of the login panel
  src/store/home.module.js
  src/store/mutations.type.js
  src/views/Home.vue
Labels: bug

#30 Training charts
  firebase_functions/.firebaserc
  firebase_functions/firebase.json
  firebase_functions/functions/.gitignore
  firebase_functions/functions/index.js
  firebase_functions/functions/package-lock.json
  firebase_functions/functions/package.json
  firebase_functions/readme.txt
  package.json
  src/charts/BarChart.js
  src/charts/DoughnutChart.js
  src/charts/LineChart.js
  src/common/Firebase.service.js
  src/store/training.module.js
  src/views/Progress.vue
Labels: enhancement

#31 Final version of charts
  src/charts/BarChart.js
  src/charts/DoughnutChart.js
  src/common/Firebase.service.js
  src/views/Progress.vue
Labels: refactoring

#35 Assets names fix (fixes #34)
  src/assets/images/Brachialis.png
  src/assets/images/Gluteusmaximus.png
Labels: ASAP, bug

#36 Develop
  .gitignore
  README.md
  firebase_functions/.firebaserc
  firebase_functions/firebase.json
  firebase_functions/functions/.gitignore
  firebase_functions/functions/index.js
  firebase_functions/functions/package-lock.json
  firebase_functions/functions/package.json
  firebase_functions/readme.txt
  package.json
  src/assets/images/Brachialis.png
  src/assets/images/Erectorspinae.png
  src/assets/images/Gluteusmaximus.png
  src/charts/BarChart.js
  src/charts/DoughnutChart.js
  src/charts/LineChart.js
  src/common/Exercises.service.js
  src/common/Firebase.service.js
  src/config/api.config.js
  src/main.js
  src/router/index.js
  src/store/actions.type.js
  src/store/home.module.js
  src/store/index.js
  src/store/measurements.module.js
  src/store/mutations.type.js
  src/store/presetCreator.module.js
  src/store/presets.module.js
  src/store/training.module.js
  src/views/Home.vue
  src/views/Measurements.vue
  src/views/Presets.vue
  src/views/PresetsCreator.vue
  src/views/Progress.vue
  src/views/Training.vue
  yarn.lock
Labels: release

#37 refactoring (resolves #19)
  src/common/Firebase.service.js
  src/store/home.module.js
  src/store/presets.module.js
  src/store/training.module.js
  src/views/Measurements.vue
  src/views/PresetsCreator.vue
Labels: refactoring

#38 merge develop to master (closes #19)
  src/common/Firebase.service.js
  src/store/home.module.js
  src/store/presets.module.js
  src/store/training.module.js
  src/views/Measurements.vue
  src/views/PresetsCreator.vue
Labels: bug, refactoring

#40 cel i opis
  docs/doc1.md
  docs/doc2.md
  website/siteConfig.js
Labels: documentation
